version: "3.9"

services:
  api:
    container_name: vigiliner_api
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    command: npm run start:dev

  web:
    container_name: vigiliner_web
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start -- --host 0.0.0.0 --port 4200
    depends_on:
      - api

  postgres:
    image: postgres:15
    container_name: vigiliner_db
    environment:
      POSTGRES_DB: vigiliner
      POSTGRES_USER: vigiliner
      POSTGRES_PASSWORD: vigiliner
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: vigiliner_redis
    ports:
      - "6379:6379"
